{% set name = "natsort" %}
{% set version = "5.4.0" %}
{% set sha256 = "9130c8954f9437a0401d4e451b4b90a874b51ce47d91ede0f2cce4db762717f9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - natsort = natsort.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - natsort
    - natsort.compat
  commands:
    - natsort -h

about:
  home: https://github.com/SethMMorton/natsort
  license: MIT
  license_file: LICENSE
  summary: 'Sort lists naturally'
  description: |
    natsort is a general utility for sorting lists naturally either as numbers
    or as versions.
  doc_url: http://natsort.readthedocs.io/
  dev_url: https://github.com/SethMMorton/natsort

extra:
  recipe-maintainers:
    - holtgrewe
    - synapticarbors
