{% set name = "natsort" %}
{% set version = "7.0.0" %}
{% set sha256 = "7207cddc510e1d5e728a7f73a0230f20a65e3346acd54856be6252291690d3ec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - natsort = natsort.__main__:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - natsort
    - natsort.compat
  commands:
    - natsort -h

about:
  home: https://github.com/SethMMorton/natsort
  license: MIT
  license_file: LICENSE
  summary: 'Sort lists naturally'
  description: |
    natsort is a general utility for sorting lists naturally either as numbers
    or as versions.
  doc_url: http://natsort.readthedocs.io/
  dev_url: https://github.com/SethMMorton/natsort

extra:
  recipe-maintainers:
    - holtgrewe
    - synapticarbors
