{% set name = "natsort" %}
{% set version = "5.1.1" %}
{% set sha256 = "9ffbfb74bf3fc3905be1b9b052ed865675651e38fcd972ed1ed5c64a02f93cbd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - natsort = natsort.__main__:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - natsort
  commands:
    - natsort -h

about:
  home: https://github.com/SethMMorton/natsort
  license: MIT
  license_file: LICENSE
  summary: 'Sort lists naturally'

  doc_url: http://natsort.readthedocs.io/
  dev_url: https://github.com/SethMMorton/natsort

extra:
  recipe-maintainers:
    - holtgrewe
    - synapticarbors
