{% set name = "natsort" %}
{% set version = "5.2.0" %}
{% set sha256 = "c960082d2145b04723041c4b85092546560538e29664dd197a1344d5b090bc91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - natsort = natsort.__main__:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - natsort
    - natsort.compat
  commands:
    - natsort --help

about:
  home: https://github.com/SethMMorton/natsort
  license: MIT
  license_file: LICENSE
  summary: 'Sort lists naturally'
  description: |
    natsort is a general utility for sorting lists naturally either as numbers
    or as versions.
  doc_url: http://pythonhosted.org/natsort/
  dev_url: https://github.com/SethMMorton/natsort

extra:
  recipe-maintainers:
    - holtgrewe
