travis:
  secure:
    BINSTAR_TOKEN: HnWKb3tiwH0o0YAOGl0AeqDpp9Rsd/C1gRRBb/FchxuqNWwkgVwkHcOh9FQpSw8fm7fReG1EV2xpFx4U8u0JV69Xtw6tCl5nDGogLTCemZXty8D7xozMpzRT0WmPLLzzUdH97yeLiVJN8iKGv6Fg/lLPVCJth7bH/8mXiDXFgrxym7AYbfK/ofBU5lxuK0j+ZvJnxnU0YuPAf89/cJ9oxPIYy63NcUqDeoJU9K6ARsmECYbNLMAmjfvGLXEXghCnbTZCtVKk5LOFDMqCQVJnFv5s8eGDgiN/uI8L4sXABwxt7UcrSetV7M5WH//zFgdaK8Ajn/a3W+ccMqT4XLmq1ev96Xj4udM/hVNU6NK1lviybi4foyqq1riyTWC8puylN3vk829FcL6RyCFCGPbu+se1Fn4uOD17qNbgFl06XUlVwokbOyh5ttQhnpP/qOi0ttNWBmJgV1wgekiihgUPvUtDQQqkc/Eei6D0PjVzPPVebLxDwuuV6L9brF8lD73v5oBe4UCWT0gAXnE9/1qMA3hoHhisEzAjBA8qqLa9tbAjfUcpt50HBWYI282EgHGlmf+PSMIN/k4aKecznmmhajGw+1WRFq20kVNrzQhR2VZp3JxMSwFMS/2AP9UwePjxtphzYTH+6ZoEoamAGL/oiGp34BOV8Ba/gMNXxGNP3C0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
