travis:
  secure:
    BINSTAR_TOKEN: MnqtuAgivH1Fsxw9er72d/AeebaUW9VUgYnQyCwBwYUrHXIV0kypCDDLXv0MQWucnaUwuwCSbbCwdC+D62nF419BxN1vmAAsC9yUZRG1SjPegRVr7f1HYt6ivMRZMFJdiRkWnVpSzDJwpTY+yua5LZpGVa/YFrTaCbSCKdoI9dhwxbQZ2EJcMXLt6muh5sJiQMZOI1PMFNIHWbcc8lxDnOZOeaaDng40mATq3wDEMJPTDSELO7UaBI0yqqADn6FEggactU0DA+ibmWDligcH6HrrvXoJ7ed4B7D7FXdNRflZoWXbvhtpu1ZPYjWWtDkLqUC2GvJ00Fdz7TaEgyvjj2+RA9isIU7bV1GGJrtRQu6alywBMAeTXDcX601wGIQ61VNu5K0VfWABlm4zjPfK7IHXqxdpYi4g3NHGQtJmSQJQE2UpKlftCHZs8cv5nKDIbkwCFKrRT4sku0/muIg+edqGxqfhfSjQR/J4G/APCfyjkec8tnn3Ncj/jLhgdBoEovgpnSAWz7r+dszc4mUUHnf2ncNWNWxs+ZMUb70B69ZMnVjPz8brPBxWOogHA+ZDIEh7qu8plOv2Fntmt88m4acEJqfmo6TcyytCD5audrR+FcJj5ICzO/ywD5ykXIpHpcpq8aYXAc3wQvYee9KsAHZbXQVD73c0uDdylV04gTM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
