travis:
  secure:
    BINSTAR_TOKEN: XXMtWe5zMfEAMauo3ci3B8sxfxjAGrCPoIr8S1FOjgoKJ/FpKTPe/ffNP/eF7rX19bLxfZoEerc6TzqByyOVMzD+bK+Ybi1EFUM0/uATjDeaLJARs5XcZv+sHQ0n5Gs8bFCr3OUjN33/K170Axx+60xN+WNKPshauw7W6XJGEn6/KEfY1Foypy2Cuu+G0C36bLhrGxXOXp7ercQyVKMAIVOVn/K5rpST+r7PycG5LOIfMQDl9p6fGLeFuAYuESKj4f6OXX/umc2QMTHba5Kf6txIbru63V7oc7CjcMxbX8Uwbz0mah3KBbwWNsksdXNRPdPNzQAjOZ1K4gy2AfQGSzc1Ud8/j/lRKWheMDPgIvI51aBtx97LFQGz9K6w2qPzyJeG7Z9rDfEPcIGFFqI+l2gmtwtNYnABPi+NWOQ8grTp7lR9DTYVvVeL1XAkx8uxq/o5Pw8VRWCf6n/7s1mw1ZkG9rrw6S6Zj+oFlzfyGlnfyW8kylj1215E3AmidIojmstSVrTxffRieP7XYVBhTyaLx/RiDv3oV4IbuTztJ9d9YVQRoGHAtyPyfLwnKPbqBYzMku6IACnjSJavX++F84F0Jl+NQiX3fUk4Q38tdUffbFCDuFObmeia7sQ4ILV/mMDsRTIqJKj/7SbnKppudYX/cvryl7f9F78JBhYkj1A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
